name: Release

on:
  push:
    branches: [release/*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: git config --local user.name "nosycode"
      - run: git config --local user.email "nosycode@gmail.com"
      - run: npm run release -- --prerelease release
      - run: git push --follow-tags origin HEAD
